name: "action-test"
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  # discussion:
  #   types: [created, edited]
  # discussion_comment:
  #   types: [created, edited]
  # pull_request_target:
  #   types: [opened, edited]
  # pull_request_review_comment:
  #   types: [created, edited]

jobs:
  test: # make sure the action works on a clean machine without building
    permissions:
      issues: write
      discussions: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        env:
          # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          IS_MODIFY_TITLE: true
          TARGET_LANGUAGE: "cmn"
          TRANSLATED_LANGUAGE: "zh-cn"
